export type Country = {
  name: string
  code: string
  dialCode: string
}

// All countries with Arabic names, sorted alphabetically by Arabic name
export const countries: Country[] = [
  { name: 'أذربيجان', code: 'AZ', dialCode: '+994' },
  { name: 'أرمينيا', code: 'AM', dialCode: '+374' },
  { name: 'أرتيريا', code: 'ER', dialCode: '+291' },
  { name: 'أسبانيا', code: 'ES', dialCode: '+34' },
  { name: 'أستراليا', code: 'AU', dialCode: '+61' },
  { name: 'أستونيا', code: 'EE', dialCode: '+372' },
  { name: 'أفغانستان', code: 'AF', dialCode: '+93' },
  { name: 'الأرجنتين', code: 'AR', dialCode: '+54' },
  { name: 'الأردن', code: 'JO', dialCode: '+962' },
  { name: 'الإمارات العربية المتحدة', code: 'AE', dialCode: '+971' },
  { name: 'الإكوادور', code: 'EC', dialCode: '+593' },
  { name: 'البحرين', code: 'BH', dialCode: '+973' },
  { name: 'البرازيل', code: 'BR', dialCode: '+55' },
  { name: 'البرتغال', code: 'PT', dialCode: '+351' },
  { name: 'البوسنة والهرسك', code: 'BA', dialCode: '+387' },
  { name: 'الجبل الأسود', code: 'ME', dialCode: '+382' },
  { name: 'الجزائر', code: 'DZ', dialCode: '+213' },
  { name: 'الدانمرك', code: 'DK', dialCode: '+45' },
  { name: 'السعودية', code: 'SA', dialCode: '+966' },
  { name: 'السلفادور', code: 'SV', dialCode: '+503' },
  { name: 'السودان', code: 'SD', dialCode: '+249' },
  { name: 'السودان الجنوبي', code: 'SS', dialCode: '+211' },
  { name: 'السويد', code: 'SE', dialCode: '+46' },
  { name: 'الصومال', code: 'SO', dialCode: '+252' },
  { name: 'الصين', code: 'CN', dialCode: '+86' },
  { name: 'العراق', code: 'IQ', dialCode: '+964' },
  { name: 'الفاتيكان', code: 'VA', dialCode: '+379' },
  { name: 'الفلبين', code: 'PH', dialCode: '+63' },
  { name: 'الكاميرون', code: 'CM', dialCode: '+237' },
  { name: 'الكويت', code: 'KW', dialCode: '+965' },
  { name: 'الجبل الأسود', code: 'ME', dialCode: '+382' },
  { name: 'المغرب', code: 'MA', dialCode: '+212' },
  { name: 'المكسيك', code: 'MX', dialCode: '+52' },
  { name: 'المملكة المتحدة', code: 'GB', dialCode: '+44' },
  { name: 'النرويج', code: 'NO', dialCode: '+47' },
  { name: 'النمسا', code: 'AT', dialCode: '+43' },
  { name: 'النيجر', code: 'NE', dialCode: '+227' },
  { name: 'الهند', code: 'IN', dialCode: '+91' },
  { name: 'الولايات المتحدة', code: 'US', dialCode: '+1' },
  { name: 'اليابان', code: 'JP', dialCode: '+81' },
  { name: 'اليمن', code: 'YE', dialCode: '+967' },
  { name: 'اليونان', code: 'GR', dialCode: '+30' },
  { name: 'أنغولا', code: 'AO', dialCode: '+244' },
  { name: 'أنتيغوا وباربودا', code: 'AG', dialCode: '+1-268' },
  { name: 'أندورا', code: 'AD', dialCode: '+376' },
  { name: 'أندونيسيا', code: 'ID', dialCode: '+62' },
  { name: 'أوزبكستان', code: 'UZ', dialCode: '+998' },
  { name: 'أوغندا', code: 'UG', dialCode: '+256' },
  { name: 'أوكرانيا', code: 'UA', dialCode: '+380' },
  { name: 'أيرلندا', code: 'IE', dialCode: '+353' },
  { name: 'أيسلندا', code: 'IS', dialCode: '+354' },
  { name: 'إثيوبيا', code: 'ET', dialCode: '+251' },
  { name: 'إيران', code: 'IR', dialCode: '+98' },
  { name: 'إيطاليا', code: 'IT', dialCode: '+39' },
  { name: 'باراغواي', code: 'PY', dialCode: '+595' },
  { name: 'باكستان', code: 'PK', dialCode: '+92' },
  { name: 'بالاو', code: 'PW', dialCode: '+680' },
  { name: 'بتسوانا', code: 'BW', dialCode: '+267' },
  { name: 'بروناي', code: 'BN', dialCode: '+673' },
  { name: 'بلجيكا', code: 'BE', dialCode: '+32' },
  { name: 'بلغاريا', code: 'BG', dialCode: '+359' },
  { name: 'بليز', code: 'BZ', dialCode: '+501' },
  { name: 'بنغلاديش', code: 'BD', dialCode: '+880' },
  { name: 'بنين', code: 'BJ', dialCode: '+229' },
  { name: 'بوتان', code: 'BT', dialCode: '+975' },
  { name: 'بورتوريكو', code: 'PR', dialCode: '+1-787' },
  { name: 'بوركينا فاسو', code: 'BF', dialCode: '+226' },
  { name: 'بوروندي', code: 'BI', dialCode: '+257' },
  { name: 'بولندا', code: 'PL', dialCode: '+48' },
  { name: 'بوليفيا', code: 'BO', dialCode: '+591' },
  { name: 'بيرو', code: 'PE', dialCode: '+51' },
  { name: 'تايلاند', code: 'TH', dialCode: '+66' },
  { name: 'تايوان', code: 'TW', dialCode: '+886' },
  { name: 'تركمانستان', code: 'TM', dialCode: '+993' },
  { name: 'تركيا', code: 'TR', dialCode: '+90' },
  { name: 'ترينيداد وتوباغو', code: 'TT', dialCode: '+1-868' },
  { name: 'تشاد', code: 'TD', dialCode: '+235' },
  { name: 'تشيلي', code: 'CL', dialCode: '+56' },
  { name: 'تنزانيا', code: 'TZ', dialCode: '+255' },
  { name: 'توغو', code: 'TG', dialCode: '+228' },
  { name: 'تونس', code: 'TN', dialCode: '+216' },
  { name: 'توفالو', code: 'TV', dialCode: '+688' },
  { name: 'جامايكا', code: 'JM', dialCode: '+1-876' },
  { name: 'جبل طارق', code: 'GI', dialCode: '+350' },
  { name: 'جامبيا', code: 'GM', dialCode: '+220' },
  { name: 'جزر القمر', code: 'KM', dialCode: '+269' },
  { name: 'جزر مارشال', code: 'MH', dialCode: '+692' },
  { name: 'جمهورية الكونغو الديمقراطية', code: 'CD', dialCode: '+243' },
  { name: 'جمهورية الدومينيكان', code: 'DO', dialCode: '+1-809' },
  { name: 'جمهورية الكونغو', code: 'CG', dialCode: '+242' },
  { name: 'جنوب أفريقيا', code: 'ZA', dialCode: '+27' },
  { name: 'جورجيا', code: 'GE', dialCode: '+995' },
  { name: 'جيبوتي', code: 'DJ', dialCode: '+253' },
  { name: 'رواندا', code: 'RW', dialCode: '+250' },
  { name: 'روسيا', code: 'RU', dialCode: '+7' },
  { name: 'رومانيا', code: 'RO', dialCode: '+40' },
  { name: 'زامبيا', code: 'ZM', dialCode: '+260' },
  { name: 'زيمبابوي', code: 'ZW', dialCode: '+263' },
  { name: 'ساحل العاج', code: 'CI', dialCode: '+225' },
  { name: 'ساموا', code: 'WS', dialCode: '+685' },
  { name: 'سان مارينو', code: 'SM', dialCode: '+378' },
  { name: 'سريلانكا', code: 'LK', dialCode: '+94' },
  { name: 'سلوفاكيا', code: 'SK', dialCode: '+421' },
  { name: 'سلوفينيا', code: 'SI', dialCode: '+386' },
  { name: 'سنغافورة', code: 'SG', dialCode: '+65' },
  { name: 'سوريا', code: 'SY', dialCode: '+963' },
  { name: 'سورينام', code: 'SR', dialCode: '+597' },
  { name: 'سوازيلاند', code: 'SZ', dialCode: '+268' },
  { name: 'سويسرا', code: 'CH', dialCode: '+41' },
  { name: 'سيشل', code: 'SC', dialCode: '+248' },
  { name: 'سينغال', code: 'SN', dialCode: '+221' },
  { name: 'صربيا', code: 'RS', dialCode: '+381' },
  { name: 'طاجيكستان', code: 'TJ', dialCode: '+992' },
  { name: 'عمان', code: 'OM', dialCode: '+968' },
  { name: 'غانا', code: 'GH', dialCode: '+233' },
  { name: 'غامبيا', code: 'GM', dialCode: '+220' },
  { name: 'غواتيمالا', code: 'GT', dialCode: '+502' },
  { name: 'غيانا', code: 'GY', dialCode: '+592' },
  { name: 'غيبي', code: 'GN', dialCode: '+224' },
  { name: 'فانواتو', code: 'VU', dialCode: '+678' },
  { name: 'فرنسا', code: 'FR', dialCode: '+33' },
  { name: 'فلسطين', code: 'PS', dialCode: '+970' },
  { name: 'فنلندا', code: 'FI', dialCode: '+358' },
  { name: 'فنزويلا', code: 'VE', dialCode: '+58' },
  { name: 'فيجي', code: 'FJ', dialCode: '+679' },
  { name: 'فيتنام', code: 'VN', dialCode: '+84' },
  { name: 'قبرص', code: 'CY', dialCode: '+357' },
  { name: 'قطر', code: 'QA', dialCode: '+974' },
  { name: 'كازاخستان', code: 'KZ', dialCode: '+7' },
  { name: 'كرواتيا', code: 'HR', dialCode: '+385' },
  { name: 'كمبوديا', code: 'KH', dialCode: '+855' },
  { name: 'كندا', code: 'CA', dialCode: '+1' },
  { name: 'كوبا', code: 'CU', dialCode: '+53' },
  { name: 'كوريا الجنوبية', code: 'KR', dialCode: '+82' },
  { name: 'كوريا الشمالية', code: 'KP', dialCode: '+850' },
  { name: 'كوستاريكا', code: 'CR', dialCode: '+506' },
  { name: 'كوسوفو', code: 'XK', dialCode: '+383' },
  { name: 'كولومبيا', code: 'CO', dialCode: '+57' },
  { name: 'كيريباتي', code: 'KI', dialCode: '+686' },
  { name: 'كينيا', code: 'KE', dialCode: '+254' },
  { name: 'لاتفيا', code: 'LV', dialCode: '+371' },
  { name: 'لاوس', code: 'LA', dialCode: '+856' },
  { name: 'لبنان', code: 'LB', dialCode: '+961' },
  { name: 'لوكسمبورغ', code: 'LU', dialCode: '+352' },
  { name: 'ليبيا', code: 'LY', dialCode: '+218' },
  { name: 'ليبيريا', code: 'LR', dialCode: '+231' },
  { name: 'ليتوانيا', code: 'LT', dialCode: '+370' },
  { name: 'ليختنشتاين', code: 'LI', dialCode: '+423' },
  { name: 'مالطا', code: 'MT', dialCode: '+356' },
  { name: 'مالي', code: 'ML', dialCode: '+223' },
  { name: 'ماليزيا', code: 'MY', dialCode: '+60' },
  { name: 'مدغشقر', code: 'MG', dialCode: '+261' },
  { name: 'مصر', code: 'EG', dialCode: '+20' },
  { name: 'مقدونيا الشمالية', code: 'MK', dialCode: '+389' },
  { name: 'ملاوي', code: 'MW', dialCode: '+265' },
  { name: 'مولدوفا', code: 'MD', dialCode: '+373' },
  { name: 'منغوليا', code: 'MN', dialCode: '+976' },
  { name: 'موريتانيا', code: 'MR', dialCode: '+222' },
  { name: 'موريشيوس', code: 'MU', dialCode: '+230' },
  { name: 'موزمبيق', code: 'MZ', dialCode: '+258' },
  { name: 'ميانمار', code: 'MM', dialCode: '+95' },
  { name: 'ناميبيا', code: 'NA', dialCode: '+264' },
  { name: 'نيبال', code: 'NP', dialCode: '+977' },
  { name: 'نيجيريا', code: 'NG', dialCode: '+234' },
  { name: 'نيكاراغوا', code: 'NI', dialCode: '+505' },
  { name: 'هايتي', code: 'HT', dialCode: '+509' },
  { name: 'هولندا', code: 'NL', dialCode: '+31' },
  { name: 'هندوراس', code: 'HN', dialCode: '+504' },
  { name: 'هونغ كونغ', code: 'HK', dialCode: '+852' },
].filter((c, i, arr) => arr.findIndex(x => x.code === c.code) === i) // dedupe
  .sort((a, b) => a.name.localeCompare(b.name, 'ar'))

export function getCountryByCode(code: string): Country | undefined {
  return countries.find((c) => c.code === code)
}
