export type TimezoneOption = {
  value: string
  label: string
}

export const timezones: TimezoneOption[] = [
  { value: 'Africa/Cairo', label: 'القاهرة (GMT+2)' },
  { value: 'Africa/Casablanca', label: 'الدار البيضاء (GMT+0/+1)' },
  { value: 'Africa/Johannesburg', label: 'جوهانسبرغ (GMT+2)' },
  { value: 'Africa/Nairobi', label: 'نيروبي (GMT+3)' },
  { value: 'Africa/Lagos', label: 'لاغوس (GMT+1)' },
  { value: 'Africa/Algiers', label: 'الجزائر (GMT+1)' },
  { value: 'Africa/Tunis', label: 'تونس (GMT+1)' },
  { value: 'Africa/Khartoum', label: 'الخرطوم (GMT+2)' },
  { value: 'Africa/Tripoli', label: 'طرابلس (GMT+2)' },
  { value: 'Asia/Dubai', label: 'دبي (GMT+4)' },
  { value: 'Asia/Riyadh', label: 'الرياض (GMT+3)' },
  { value: 'Asia/Qatar', label: 'قطر (GMT+3)' },
  { value: 'Asia/Kuwait', label: 'الكويت (GMT+3)' },
  { value: 'Asia/Baghdad', label: 'بغداد (GMT+3)' },
  { value: 'Asia/Beirut', label: 'بيروت (GMT+3)' },
  { value: 'Asia/Damascus', label: 'دمشق (GMT+3)' },
  { value: 'Asia/Amman', label: 'عمّان (GMT+3)' },
  { value: 'Asia/Jerusalem', label: 'القدس (GMT+2/+3)' },
  { value: 'Asia/Tehran', label: 'طهران (GMT+3:30)' },
  { value: 'Asia/Istanbul', label: 'إسطنبول (GMT+3)' },
  { value: 'Asia/Riyadh', label: 'الرياض (GMT+3)' },
  { value: 'Asia/Karachi', label: 'كراتشي (GMT+5)' },
  { value: 'Asia/Kolkata', label: 'كولكاتا (GMT+5:30)' },
  { value: 'Asia/Dhaka', label: 'دكا (GMT+6)' },
  { value: 'Asia/Bangkok', label: 'بانكوك (GMT+7)' },
  { value: 'Asia/Jakarta', label: 'جاكرتا (GMT+7)' },
  { value: 'Asia/Shanghai', label: 'شنغهاي (GMT+8)' },
  { value: 'Asia/Hong_Kong', label: 'هونغ كونغ (GMT+8)' },
  { value: 'Asia/Singapore', label: 'سنغافورة (GMT+8)' },
  { value: 'Asia/Tokyo', label: 'طوكيو (GMT+9)' },
  { value: 'Asia/Seoul', label: 'سيول (GMT+9)' },
  { value: 'Europe/London', label: 'لندن (GMT+0/+1)' },
  { value: 'Europe/Paris', label: 'باريس (GMT+1/+2)' },
  { value: 'Europe/Berlin', label: 'برلين (GMT+1/+2)' },
  { value: 'Europe/Madrid', label: 'مدريد (GMT+1/+2)' },
  { value: 'Europe/Rome', label: 'روما (GMT+1/+2)' },
  { value: 'Europe/Amsterdam', label: 'أمستردام (GMT+1/+2)' },
  { value: 'Europe/Brussels', label: 'بروكسل (GMT+1/+2)' },
  { value: 'Europe/Moscow', label: 'موسكو (GMT+3)' },
  { value: 'Europe/Athens', label: 'أثينا (GMT+2/+3)' },
  { value: 'Europe/Stockholm', label: 'ستوكهولم (GMT+1/+2)' },
  { value: 'Europe/Oslo', label: 'أوسلو (GMT+1/+2)' },
  { value: 'Europe/Copenhagen', label: 'كوبنهاغن (GMT+1/+2)' },
  { value: 'Europe/Helsinki', label: 'هلسنكي (GMT+2/+3)' },
  { value: 'Europe/Warsaw', label: 'وارسو (GMT+1/+2)' },
  { value: 'Europe/Vienna', label: 'فيينا (GMT+1/+2)' },
  { value: 'Europe/Lisbon', label: 'لشبونة (GMT+0/+1)' },
  { value: 'Europe/Dublin', label: 'دبلن (GMT+0/+1)' },
  { value: 'America/New_York', label: 'نيويورك (GMT-5/-4)' },
  { value: 'America/Chicago', label: 'شيكاغو (GMT-6/-5)' },
  { value: 'America/Denver', label: 'دنفر (GMT-7/-6)' },
  { value: 'America/Los_Angeles', label: 'لوس أنجلوس (GMT-8/-7)' },
  { value: 'America/Toronto', label: 'تورنتو (GMT-5/-4)' },
  { value: 'America/Vancouver', label: 'فانكوفر (GMT-8/-7)' },
  { value: 'America/Mexico_City', label: 'مكسيكو سيتي (GMT-6)' },
  { value: 'America/Sao_Paulo', label: 'ساو باولو (GMT-3)' },
  { value: 'America/Argentina/Buenos_Aires', label: 'بوينس آيرس (GMT-3)' },
  { value: 'America/Bogota', label: 'بوغوتا (GMT-5)' },
  { value: 'America/Lima', label: 'ليما (GMT-5)' },
  { value: 'America/Santiago', label: 'سانتياغو (GMT-4/-3)' },
  { value: 'Australia/Sydney', label: 'سيدني (GMT+10/+11)' },
  { value: 'Australia/Melbourne', label: 'ملبورن (GMT+10/+11)' },
  { value: 'Australia/Perth', label: 'بيرث (GMT+8)' },
  { value: 'Pacific/Auckland', label: 'أوكلاند (GMT+12/+13)' },
  { value: 'UTC', label: 'التوقيت العالمي (UTC)' },
].filter((t, i, arr) => arr.findIndex(x => x.value === t.value) === i)
  .sort((a, b) => a.label.localeCompare(b.label, 'ar'))
